Dx11System.cpp
wchar_t szWindowClass[][]
Referenced by Dx11System::DestroyDxWindow, Dx11System::InitializeDxWindow.
Dx11System* DxSystemHandle
DWORD WindowStyleEx(bool fullscreen)
Referenced by Dx11System::InitializeDxWindow.
DWORD WindowStyle(bool fullscreen)
Referenced by Dx11System::InitializeDxWindow.
LRESULT CALLBACK DxWndProc(HWND hwnd, UINT umsg, WPARAM wparam, LPARAM lparam)
References Dx11System::MessageHandler.
Referenced by Dx11System::InitializeDxWindow.