Dx11Graphics
float Dx11Graphics::m_ScreenDepth
Referenced by Initialize.
float Dx11Graphics::m_ScreenNear
Referenced by Initialize.
bool Dx11Graphics::m_vSync
Referenced by Initialize.
D3D11Engine Dx11Graphics::m_DxEngine
Referenced by Destroy, Initialize, Render, UpdateFrame.
Dx11Graphics::Dx11Graphics()
Dx11Graphics::~Dx11Graphics()
bool Dx11Graphics::Initialize(HWND hWnd, int Width, int Height, bool fullscreen)
References D3D11Engine::Initialize, m_DxEngine, m_ScreenDepth, m_ScreenNear, m_vSync.
Referenced by Dx11System::Initialize.
void Dx11Graphics::Destroy()
References D3D11Engine::Destroy, m_DxEngine.
Referenced by Dx11System::Destroy.
bool Dx11Graphics::UpdateFrame()
References m_DxEngine, Render, D3D11Engine::UpdateFrame.
Referenced by Dx11System::UpdateFrame.
bool Dx11Graphics::Render()
References D3D11Engine::BeginScene, D3D11Engine::EndScene, m_DxEngine, D3D11Engine::Render.
Referenced by UpdateFrame.