DX11Helper.h
NAME_D3D11_OBJECT
NAME_D3D11_OBJECT_INDEXED
void ThrowIfFailed(HRESULT hr, LPCWSTR szMsg=nullptr)
Referenced by D3D11Engine::LoadAssets, D3D11Engine::LoadPipeline.
void GetAssetsPath(_Out_writes_(pathSize) WCHAR *path, UINT pathSize)
Referenced by D3D11Engine::D3D11Engine.
HRESULT ReadDataFromFile(LPCWSTR filename, byte **data, UINT *size)