Dx11Input
bool Dx11Input::m_bKeyDown[256][256]
Referenced by Initialize, IsKeyDown, KeyDown, KeyUp.
Dx11Input::Dx11Input()
Dx11Input::~Dx11Input()
bool Dx11Input::Initialize(HWND m_hWnd)
References m_bKeyDown.
Referenced by Dx11System::Initialize.
void Dx11Input::Destroy()
Referenced by Dx11System::Destroy.
bool Dx11Input::IsKeyDown(unsigned int keyCode)
References m_bKeyDown.
Referenced by Dx11System::UpdateFrame.
void Dx11Input::KeyDown(unsigned int keyCode)
References m_bKeyDown.
Referenced by Dx11System::MessageHandler.
void Dx11Input::KeyUp(unsigned int keyCode)
References m_bKeyDown.
Referenced by Dx11System::MessageHandler.