Dx11System
HINSTANCE Dx11System::m_hInstance
Referenced by DestroyDxWindow, InitializeDxWindow.
std::wstring Dx11System::m_strCmdLine
HWND Dx11System::m_hWnd
Referenced by DestroyDxWindow, Initialize, InitializeDxWindow.
Dx11Input Dx11System::m_Input
Referenced by Destroy, Initialize, MessageHandler, UpdateFrame.
Dx11Graphics Dx11System::m_Graphics
Referenced by Destroy, Initialize, UpdateFrame.
SIZE Dx11System::m_szWindow
Referenced by Initialize, InitializeDxWindow.
bool Dx11System::m_bFullScreen
Referenced by DestroyDxWindow, Initialize, InitializeDxWindow.
bool Dx11System::m_bRuning
Referenced by Run.
Dx11System::Dx11System(_In_ HINSTANCE hInstance, _In_ LPCWSTR lpCmdLine)
Dx11System::~Dx11System()
LRESULT Dx11System::MessageHandler(HWND hwnd, UINT umsg, WPARAM wparam, LPARAM lparam)
References Dx11Input::KeyDown, Dx11Input::KeyUp, m_Input.
Referenced by DxWndProc.
bool Dx11System::Initialize(LPCWSTR szTitle)
References Dx11Input::Initialize, Dx11Graphics::Initialize, InitializeDxWindow, m_bFullScreen, m_Graphics, m_hWnd, m_Input, m_szWindow.
Referenced by wWinMain.
void Dx11System::Run()
References m_bRuning, UpdateFrame.
Referenced by wWinMain.
void Dx11System::Destroy()
References Dx11Input::Destroy, Dx11Graphics::Destroy, DestroyDxWindow, m_Graphics, m_Input.
Referenced by wWinMain.
bool Dx11System::UpdateFrame()
References Dx11Input::IsKeyDown, m_Graphics, m_Input, Dx11Graphics::UpdateFrame.
Referenced by Run.
bool Dx11System::InitializeDxWindow(LPCWSTR szTitle)
References DxWndProc, m_bFullScreen, m_hInstance, m_hWnd, m_szWindow, szWindowClass, WindowStyle, WindowStyleEx.
Referenced by Initialize.
void Dx11System::DestroyDxWindow()
References m_bFullScreen, m_hInstance, m_hWnd, szWindowClass.
Referenced by Destroy.