D3D11Engine
std::wstring D3D11Engine::m_AssetsPath
Referenced by D3D11Engine, GetAssetFullPath.
float D3D11Engine::m_AspectRatio
Referenced by Initialize, LoadAssets.
float D3D11Engine::m_FOV
Referenced by Initialize.
HWND D3D11Engine::m_hWnd
Referenced by Initialize.
UINT D3D11Engine::m_Width
Referenced by GetHardwareAdapter, Initialize.
UINT D3D11Engine::m_Height
Referenced by GetHardwareAdapter, Initialize.
D3D11_VIEWPORT D3D11Engine::m_Viewport
Referenced by BeginScene, Initialize.
XMMATRIX D3D11Engine::m_matProjection
Referenced by Initialize.
XMMATRIX D3D11Engine::m_matWorld
Referenced by Initialize.
XMMATRIX D3D11Engine::m_matOrtho
Referenced by Initialize.
bool D3D11Engine::m_Warp
Referenced by LoadPipeline.
bool D3D11Engine::m_bVsync
Referenced by EndScene, Initialize.
bool D3D11Engine::m_bFullScreen
Referenced by Initialize.
int D3D11Engine::m_VideoMemory
Referenced by LoadPipeline.
std::wstring D3D11Engine::m_VideoCard
Referenced by LoadPipeline.
DXGI_FORMAT D3D11Engine::m_BufferFormat
Referenced by GetHardwareAdapter.
DXGI_FORMAT D3D11Engine::m_DepthStencilFormat
ComPtr<IDXGISwapChain> D3D11Engine::m_SwapChain
Referenced by EndScene.
ComPtr<ID3D11Device> D3D11Engine::m_Device
Referenced by EndScene, LoadAssets.
ComPtr<ID3D11DeviceContext> D3D11Engine::m_Context
Referenced by BeginScene, Render.
ComPtr<ID3D11RenderTargetView> D3D11Engine::m_RenderTargetView
Referenced by BeginScene.
ComPtr<ID3D11DepthStencilState> D3D11Engine::m_DepthStencilState
Referenced by BeginScene.
ComPtr<ID3D11DepthStencilView> D3D11Engine::m_DepthStencilView
Referenced by BeginScene.
ComPtr<ID3D11RasterizerState> D3D11Engine::m_RasterizerState
Referenced by BeginScene.
ComPtr<ID3D11Buffer> D3D11Engine::m_VertexBuffer
Referenced by BeginScene, LoadAssets.
UINT D3D11Engine::m_VertexCount
Referenced by LoadAssets.
ComPtr<ID3D11Buffer> D3D11Engine::m_IndexBuffer
Referenced by BeginScene, LoadAssets.
UINT D3D11Engine::m_IndexCount
Referenced by LoadAssets, Render.
ComPtr<ID3D11InputLayout> D3D11Engine::m_InputLayout
Referenced by BeginScene, LoadAssets.
ComPtr<ID3D11VertexShader> D3D11Engine::m_VertexShader
Referenced by BeginScene, LoadAssets.
ComPtr<ID3D11PixelShader> D3D11Engine::m_PixelShader
Referenced by BeginScene, LoadAssets.
UINT D3D11Engine::m_FrameIndex
D3D11Engine::D3D11Engine()
References GetAssetsPath, m_AssetsPath.
D3D11Engine::~D3D11Engine()
void D3D11Engine::BeginScene(float cr, float cg, float cb, float ca)
References m_Context, m_DepthStencilState, m_DepthStencilView, m_IndexBuffer, m_InputLayout, m_PixelShader, m_RasterizerState, m_RenderTargetView, m_VertexBuffer, m_VertexShader, m_Viewport.
Referenced by Dx11Graphics::Render.
void D3D11Engine::Render()
References m_Context, m_IndexCount.
Referenced by Dx11Graphics::Render.
void D3D11Engine::EndScene()
References m_bVsync, m_Device, m_SwapChain.
Referenced by Dx11Graphics::Render.
ID3D11Device* D3D11Engine::Device()
bool D3D11Engine::Initialize(HWND hWnd, int Width, int Height, float ScreenDepth, float ScreenNear, bool vSync, bool fullscreen)
References LoadAssets, LoadPipeline, m_AspectRatio, m_bFullScreen, m_bVsync, m_FOV, m_Height, m_hWnd, m_matOrtho, m_matProjection, m_matWorld, m_Viewport, m_Width.
Referenced by Dx11Graphics::Initialize.
void D3D11Engine::Destroy()
Referenced by Dx11Graphics::Destroy.
bool D3D11Engine::UpdateFrame()
Referenced by Dx11Graphics::UpdateFrame.
std::wstring D3D11Engine::GetAssetFullPath(LPCWSTR assetName)
References m_AssetsPath.
Referenced by LoadAssets.
HRESULT D3D11Engine::GetHardwareAdapter(IDXGIFactory4 *pFactory, IDXGIAdapter1 **ppAdapter, IDXGIOutput **ppOutput, DXGI_MODE_DESC *pModeDesc)
References m_BufferFormat, m_Height, m_Width.
Referenced by LoadPipeline.
bool D3D11Engine::LoadPipeline()
References GetHardwareAdapter, m_VideoCard, m_VideoMemory, m_Warp, ThrowIfFailed.
Referenced by Initialize.
bool D3D11Engine::LoadAssets()
References GetAssetFullPath, m_AspectRatio, m_Device, m_IndexBuffer, m_IndexCount, m_InputLayout, m_PixelShader, m_VertexBuffer, m_VertexCount, m_VertexShader, ThrowIfFailed.
Referenced by Initialize.